# Generated by Django 3.0.7 on 2020-06-15 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date']},
        ),
    ]
